# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "25081560b143578db96ae630510fb4a7"
application_url = "http://localhost:3000"
embedded = false
name = "GRIT Automation"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "http://localhost:3000/callback" ]
